service: serverless-nodejs-starter
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}

functions:
  hello:
    handler: src/handlers/main.hello
    events:
      - http:
          path: hello
          method: get