service:
  name: serverless-nodejs-starter

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}

functions:
  hello:
    handler: src/handlers/main.hello
    events:
      - http:
          path: hello
          method: get

custom:
  bundle:
    sourcemaps: false
    linting: false